/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rtj06if66JG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import Image from "next/image";

export function Hero() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      
      <main className="flex-1">
        <section
          className="bg-primary py-12 md:py-24 lg:py-32 text-center text-primary-foreground">
          <div className="container px-4 md:px-6">
            <div className="max-w-3xl mx-auto space-y-4 animate-fade-in">
              <h1 className="text-4xl md:text-5xl font-bold">Consulting Firm</h1>
              <p className="text-lg md:text-xl">
                Empowering organizations to navigate the complexities of sustainability, risk assessment, and beyond.
              </p>
              <div className="flex justify-center gap-2 mt-6">
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary-foreground px-6 py-3 text-sm font-medium text-primary transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}>
                  Get Started
                </Link>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md border border-primary-foreground px-6 py-3 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary-foreground hover:text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}>
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section id="topics" className="py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="max-w-3xl mx-auto space-y-8 animate-fade-in">
              <div className="text-center">
                <h2 className="text-3xl md:text-4xl font-bold">Our Areas of Expertise</h2>
                <p className="text-muted-foreground mt-2 text-lg md:text-xl">
                  Discover how we can help your organization navigate the complex landscape of sustainability, risk
                  assessment, and more.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <HazeIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Hazid</h3>
                  <p className="text-muted-foreground">
                    Comprehensive hazard identification to proactively manage risks.
                  </p>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <HazeIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Hazop</h3>
                  <p className="text-muted-foreground">
                    In-depth analysis of potential hazards and operability issues.
                  </p>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <ScanIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">SIL Assessment</h3>
                  <p className="text-muted-foreground">
                    Evaluate the safety integrity level of your systems and processes.
                  </p>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <RatioIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Quantitative Risk Assessment</h3>
                  <p className="text-muted-foreground">Comprehensive analysis of risks to inform decision-making.</p>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <WaypointsIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Our Pathway</h3>
                  <p className="text-muted-foreground">
                    Tailored solutions to guide your organization's sustainability journey.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="esg-services" className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="max-w-3xl mx-auto space-y-8 animate-fade-in">
              <div className="text-center">
                <h2 className="text-3xl md:text-4xl font-bold">ESG Services</h2>
                <p className="text-muted-foreground mt-2 text-lg md:text-xl">
                  Comprehensive solutions to help your organization navigate the evolving landscape of environmental,
                  social, and governance (ESG) requirements.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <MapIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Sustainability Road Map Development</h3>
                  <p className="text-muted-foreground">
                    Identify sustainability opportunities and challenges, prioritize initiatives, and create a roadmap
                    for implementation.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <StickerIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Stakeholder Engagement</h3>
                  <p className="text-muted-foreground">
                    Facilitate meaningful dialogues with key stakeholders to align on sustainability priorities.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <AccessibilityIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Materiality Assessment</h3>
                  <p className="text-muted-foreground">
                    Identify and prioritize the most significant ESG issues for your organization.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <RecycleIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Sustainability Reporting</h3>
                  <p className="text-muted-foreground">
                    Develop comprehensive sustainability reports to communicate your organization's ESG performance.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <BracketsIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Business Responsibility and Sustainable Reporting (BRSR)</h3>
                  <p className="text-muted-foreground">
                    Ensure compliance with the latest BRSR guidelines and requirements.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <DiscIcon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">Carbon Disclosure Project (CDP)</h3>
                  <p className="text-muted-foreground">
                    Assist with CDP reporting to showcase your organization's environmental impact and performance.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
                <div className="bg-background rounded-lg shadow-sm p-6 flex flex-col gap-4">
                  <Table2Icon className="w-12 h-12 text-primary" />
                  <h3 className="text-xl font-semibold">TCFD & SASB Reporting</h3>
                  <p className="text-muted-foreground">
                    Ensure compliance with the latest TCFD and SASB reporting frameworks.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="sustainability" className="py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="max-w-3xl mx-auto space-y-8 animate-fade-in">
              <div className="text-center">
                <h2 className="text-3xl md:text-4xl font-bold">Sustainability Road Map Development</h2>
                <p className="text-muted-foreground mt-2 text-lg md:text-xl">
                  Unlock your organization's sustainability potential with our comprehensive approach.
                </p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div>
                  <h3 className="text-2xl font-semibold">Identify Opportunities and Challenges</h3>
                  <p className="text-muted-foreground mt-2">
                    Our team will work closely with your organization to understand your current sustainability
                    landscape, identify areas of opportunity, and pinpoint potential challenges.
                  </p>
                </div>
                <div>
                  <h3 className="text-2xl font-semibold">Prioritize Initiatives</h3>
                  <p className="text-muted-foreground mt-2">
                    We'll help you prioritize the most impactful sustainability initiatives based on your organization's
                    goals, resources, and industry best practices.
                  </p>
                </div>
                <div>
                  <h3 className="text-2xl font-semibold">Create a Roadmap</h3>
                  <p className="text-muted-foreground mt-2">
                    Our experts will develop a comprehensive roadmap to guide your organization's sustainability
                    journey, including detailed implementation plans and key milestones.
                  </p>
                </div>
                <div>
                  <h3 className="text-2xl font-semibold">Ongoing Support</h3>
                  <p className="text-muted-foreground mt-2">
                    We'll provide ongoing support and guidance to ensure the successful execution of your sustainability
                    initiatives and help you adapt to evolving industry standards and regulations.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="max-w-3xl mx-auto space-y-8 animate-fade-in">
              <div className="text-center">
                <h2 className="text-3xl md:text-4xl font-bold">Get in Touch</h2>
                <p className="text-muted-foreground mt-2 text-lg md:text-xl">
                  Let's discuss how we can help your organization achieve its sustainability and risk management goals.
                </p>
              </div>
              <form className="grid gap-4">
                <div className="grid grid-cols-1 sm:grid-cols" />
              </form>
            </div>
          </div>
        </section>

        <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="animate-fade-up">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">About Us</h2>
                <p className="max-w-[600px] text-muted-foreground md:text-lg">
                  Consulting Firm is a leading provider of sustainability and risk assessment services. Our team of
                  experts has decades of experience in helping organizations achieve their environmental, social, and
                  governance (ESG) goals.
                </p>
                <div className="mt-6 flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Contact Us
                  </Link>
                </div>
              </div>
              <div className="animate-fade-up">
                <Image
                  src="/placeholder.svg"
                  width="550"
                  height="400"
                  alt="About Us"
                  className="mx-auto aspect-[4/3] overflow-hidden rounded-xl object-cover"
                />
              </div>
            </div>
            </div>
      </main>
    </div>)
  );
}

function AccessibilityIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>)
  );
}


function BracketsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 3h3v18h-3" />
      <path d="M8 21H5V3h3" />
    </svg>)
  );
}


function DiscIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>)
  );
}


function HazeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m5.2 6.2 1.4 1.4" />
      <path d="M2 13h2" />
      <path d="M20 13h2" />
      <path d="m17.4 7.6 1.4-1.4" />
      <path d="M22 17H2" />
      <path d="M22 21H2" />
      <path d="M16 13a4 4 0 0 0-8 0" />
      <path d="M12 5V2.5" />
    </svg>)
  );
}


function MapIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" />
      <path d="M15 5.764v15" />
      <path d="M9 3.236v15" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function RatioIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="12" height="20" x="6" y="2" rx="2" />
      <rect width="20" height="12" x="2" y="6" rx="2" />
    </svg>)
  );
}


function RecycleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5" />
      <path
        d="M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12" />
      <path d="m14 16-3 3 3 3" />
      <path d="M8.293 13.596 7.196 9.5 3.1 10.598" />
      <path
        d="m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843" />
      <path d="m13.378 9.633 4.096 1.098 1.097-4.096" />
    </svg>)
  );
}


function ScanIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 7V5a2 2 0 0 1 2-2h2" />
      <path d="M17 3h2a2 2 0 0 1 2 2v2" />
      <path d="M21 17v2a2 2 0 0 1-2 2h-2" />
      <path d="M7 21H5a2 2 0 0 1-2-2v-2" />
    </svg>)
  );
}


function StickerIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15.5 3H5a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2V8.5L15.5 3Z" />
      <path d="M14 3v4a2 2 0 0 0 2 2h4" />
      <path d="M8 13h0" />
      <path d="M16 13h0" />
      <path d="M10 16s.8 1 2 1c1.3 0 2-1 2-1" />
    </svg>)
  );
}


function Table2Icon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2V9M9 21H5a2 2 0 0 1-2-2V9m0 0h18" />
    </svg>)
  );
}


function WaypointsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="4.5" r="2.5" />
      <path d="m10.2 6.3-3.9 3.9" />
      <circle cx="4.5" cy="12" r="2.5" />
      <path d="M7 12h10" />
      <circle cx="19.5" cy="12" r="2.5" />
      <path d="m13.8 17.7 3.9-3.9" />
      <circle cx="12" cy="19.5" r="2.5" />
    </svg>)
  );
}
