// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/FNhb6RL4y6T
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Libre_Franklin } from 'next/font/google'

// libre_franklin({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import Link from "next/link"
// import { Button } from "@/components/ui/button"
// import { Card } from "@/components/ui/card"
// import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
// import { Input } from "@/components/ui/input"
// import { Textarea } from "@/components/ui/textarea"
// import Image from "next/image"

// export function OurService() {
//   return (
//     (<div className="flex flex-col min-h-[100dvh]">
//       <header
//         className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
//         <Link href="#" className="text-2xl font-bold" prefetch={false}>
//           Consulting Firm
//         </Link>
//         <nav className="hidden md:flex gap-6">
//           <Link href="#" className="hover:underline" prefetch={false}>
//             Services
//           </Link>
//           <Link href="#" className="hover:underline" prefetch={false}>
//             Sustainability
//           </Link>
//           <Link href="#" className="hover:underline" prefetch={false}>
//             About
//           </Link>
//           <Link href="#" className="hover:underline" prefetch={false}>
//             Contact
//           </Link>
//         </nav>
//         <Button variant="outline" className="md:hidden">
//           <MenuIcon className="w-6 h-6" />
//           <span className="sr-only">Toggle Menu</span>
//         </Button>
//       </header>
//       <main className="flex-1">
//         <section
//           id="hero"
//           className="bg-gradient-to-r from-primary to-primary/80 text-primary-foreground py-12 md:py-24 lg:py-32 xl:py-48">
//           <div className="container px-4 md:px-6">
//             <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
//               <div className="space-y-4 animate-fade-up">
//                 <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl xl:text-6xl">Consulting Firm</h1>
//                 <p className="max-w-[600px] text-lg md:text-xl">
//                   We specialize in providing comprehensive sustainability and risk assessment services to help
//                   organizations achieve their environmental, social, and governance (ESG) goals.
//                 </p>
//               </div>
//               <div className="animate-fade-up">
//                 <Image
//                   src="/placeholder.svg"
//                   width="550"
//                   height="400"
//                   alt="Hero Image"
//                   className="mx-auto aspect-[4/3] overflow-hidden rounded-xl object-cover" />
//               </div>
//             </div>
//           </div>
//         </section>
//         <section id="services" className="bg-background py-12 md:py-24 lg:py-32">
//           <div className="container px-4 md:px-6">
//             <div className="space-y-6">
//               <div className="animate-fade-up">
//                 <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Our Services</h2>
//                 <p className="max-w-[600px] text-muted-foreground md:text-lg">
//                   We offer a wide range of sustainability and risk assessment services to help organizations achieve
//                   their goals.
//                 </p>
//               </div>
//               <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 animate-fade-up">
//                 <Card className="p-6 space-y-4">
//                   <HazeIcon className="w-12 h-12 text-primary" />
//                   <h3 className="text-xl font-semibold">HAZID</h3>
//                   <p className="text-muted-foreground">
//                     Comprehensive hazard identification to proactively manage risks.
//                   </p>
//                 </Card>
//                 <Card className="p-6 space-y-4">
//                   <HazeIcon className="w-12 h-12 text-primary" />
//                   <h3 className="text-xl font-semibold">HAZOP</h3>
//                   <p className="text-muted-foreground">
//                     In-depth analysis of potential hazards and operability issues.
//                   </p>
//                 </Card>
//                 <Card className="p-6 space-y-4">
//                   <HazeIcon className="w-12 h-12 text-primary" />
//                   <h3 className="text-xl font-semibold">SIL Assessment</h3>
//                   <p className="text-muted-foreground">
//                     Determine the required Safety Integrity Level for your systems.
//                   </p>
//                 </Card>
//                 <Card className="p-6 space-y-4">
//                   <HazeIcon className="w-12 h-12 text-primary" />
//                   <h3 className="text-xl font-semibold">Quantitative Risk Assessment</h3>
//                   <p className="text-muted-foreground">Comprehensive analysis of risks and their potential impacts.</p>
//                 </Card>
//                 <Card className="p-6 space-y-4">
//                   <HazeIcon className="w-12 h-12 text-primary" />
//                   <h3 className="text-xl font-semibold">ESG Services</h3>
//                   <p className="text-muted-foreground">
//                     Helping organizations achieve their environmental, social, and governance goals.
//                   </p>
//                 </Card>
//               </div>
//             </div>
//           </div>
//         </section>
//         <section id="sustainability" className="bg-muted py-12 md:py-24 lg:py-32">
//           <div className="container px-4 md:px-6">
//             <div className="space-y-6">
//               <div className="animate-fade-up">
//                 <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Sustainability Road Map Development</h2>
//                 <p className="max-w-[600px] text-muted-foreground md:text-lg">
//                   We understand the importance of a well-defined sustainability roadmap for organizations. Our experts
//                   can help you develop a comprehensive plan to achieve your sustainability goals.
//                 </p>
//               </div>
//               <div className="animate-fade-up">
//                 <Collapsible className="rounded-lg border bg-background p-6 shadow-sm">
//                   <CollapsibleTrigger className="flex items-center justify-between">
//                     <h3 className="text-xl font-semibold">ESG Services</h3>
//                     <ChevronDownIcon
//                       className="w-5 h-5 text-muted-foreground transition-transform duration-300 group-[data-state=open]:rotate-180" />
//                   </CollapsibleTrigger>
//                   <CollapsibleContent className="pt-4 space-y-4">
//                     <div>
//                       <h4 className="text-lg font-semibold">Environmental</h4>
//                       <p className="text-muted-foreground">
//                         We help organizations assess their environmental impact and develop strategies to reduce their
//                         carbon footprint, improve energy efficiency, and promote sustainable practices.
//                       </p>
//                     </div>
//                     <div>
//                       <h4 className="text-lg font-semibold">Social</h4>
//                       <p className="text-muted-foreground">
//                         Our team can assist in evaluating an organization's social impact, including employee
//                         well-being, community engagement, and diversity and inclusion initiatives.
//                       </p>
//                     </div>
//                     <div>
//                       <h4 className="text-lg font-semibold">Governance</h4>
//                       <p className="text-muted-foreground">
//                         We provide guidance on implementing robust governance structures, ensuring transparency, and
//                         aligning decision-making with sustainability principles.
//                       </p>
//                     </div>
//                   </CollapsibleContent>
//                 </Collapsible>
//               </div>
//             </div>
//           </div>
//         </section>
//         <section id="about" className="bg-background py-12 md:py-24 lg:py-32">
//           <div className="container px-4 md:px-6">
//             <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
//               <div className="animate-fade-up">
//                 <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">About Us</h2>
//                 <p className="max-w-[600px] text-muted-foreground md:text-lg">
//                   Consulting Firm is a leading provider of sustainability and risk assessment services. Our team of
//                   experts has decades of experience in helping organizations achieve their environmental, social, and
//                   governance (ESG) goals.
//                 </p>
//                 <div className="mt-6 flex flex-col gap-2 min-[400px]:flex-row">
//                   <Link
//                     href="#"
//                     className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                     prefetch={false}>
//                     Learn More
//                   </Link>
//                   <Link
//                     href="#"
//                     className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                     prefetch={false}>
//                     Contact Us
//                   </Link>
//                 </div>
//               </div>
//               <div className="animate-fade-up">
//                 <Image
//                   src="/placeholder.svg"
//                   width="550"
//                   height="400"
//                   alt="About Us"
//                   className="mx-auto aspect-[4/3] overflow-hidden rounded-xl object-cover" />
//               </div>
//             </div>
//           </div>
//         </section>
//         <section id="contact" className="bg-muted py-12 md:py-24 lg:py-32 border-t">
//           <div className="container px-4 md:px-6">
//             <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 animate-fade-up">
//               <div className="space-y-4">
//                 <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Get in Touch</h2>
//                 <p className="text-muted-foreground md:text-lg">
//                   Have a project in mind or need our expertise? Contact us today.
//                 </p>
//               </div>
//               <div className="sm:col-span-2 lg:col-span-2 space-y-4">
//                 <form className="grid gap-4">
//                   <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
//                     <Input type="text" placeholder="Name" className="max-w-lg flex-1" />
//                     <Input type="email" placeholder="Email" className="max-w-lg flex-1" />
//                   </div>
//                   <Textarea placeholder="Message" className="max-w-lg flex-1" />
//                   <Button type="submit">Submit</Button>
//                 </form>
//               </div>
//             </div>
//           </div>
//         </section>
//       </main>
//       <footer className="bg-primary text-primary-foreground py-6 px-4 md:px-6">
//         <div
//           className="container flex flex-col sm:flex-row items-center justify-between">
//           <p className="text-sm">&copy; 2024 Consulting Firm. All rights reserved.</p>
//           <nav className="flex gap-4 sm:gap-6 mt-4 sm:mt-0">
//             <Link href="#" className="hover:underline" prefetch={false}>
//               Privacy
//             </Link>
//             <Link href="#" className="hover:underline" prefetch={false}>
//               Terms
//             </Link>
//           </nav>
//         </div>
//       </footer>
//     </div>)
//   );
// }

// function ChevronDownIcon(props) {
//   return (
//     (<svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round">
//       <path d="m6 9 6 6 6-6" />
//     </svg>)
//   );
// }


// function HazeIcon(props) {
//   return (
//     (<svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round">
//       <path d="m5.2 6.2 1.4 1.4" />
//       <path d="M2 13h2" />
//       <path d="M20 13h2" />
//       <path d="m17.4 7.6 1.4-1.4" />
//       <path d="M22 17H2" />
//       <path d="M22 21H2" />
//       <path d="M16 13a4 4 0 0 0-8 0" />
//       <path d="M12 5V2.5" />
//     </svg>)
//   );
// }


// function MenuIcon(props) {
//   return (
//     (<svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round">
//       <line x1="4" x2="20" y1="12" y2="12" />
//       <line x1="4" x2="20" y1="6" y2="6" />
//       <line x1="4" x2="20" y1="18" y2="18" />
//     </svg>)
//   );
// }
